# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LDR_App_client' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LDR_App_client
  rn_path = '../node_modules/react-native'
  pod 'Yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

#  target 'LDR_App_client-tvOSTests' do
#    inherit! :search_paths
#    # Pods for testing
#
#  end

  target 'LDR_App_clientTests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
end

# very important to have, unless you removed React dependencies for Libraries
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

# target 'LDR_App_client-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!
#
#   # Pods for LDR_App_client-tvOS
#
#   target 'LDR_App_client-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
#
# end
